openapi: 3.0.0
info:
  title: Mobile Financial Service API
  version: 1.0.0
  description: Swagger docs for MFS backend

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


paths:
  /api/register:
    post:
      tags: [Auth]
      summary: Register a new user or agent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                mobileNumber:
                  type: string
                email:
                  type: string
                pin:
                  type: string
                nid:
                  type: string
                role:
                  type: string
                  enum: [User, Agent]
      responses:
        "201":
          description: Successful registration

  /api/login:
    post:
      tags: [Auth]
      summary: Login with mobile/email and PIN
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                identifier:
                  type: string
                pin:
                  type: string
      responses:
        "200":
          description: Successful login
  
  /api/logout:
    post:
      tags: [Auth]
      summary: Logout the user and invalidate session token
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful logout
        "401":
          description: Unauthorized
  
  /api/send-money:
    post:
      tags: [Transaction]
      summary: Send money from one user to another
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                receiverMobileNumber:
                  type: string
                amount:
                  type: number
                pin:
                  type: string
      responses:
        "201":
          description: Send Money successful
        "400":
          description: Validation or insufficient balance
        "401":
          description: Unauthorized or incorrect PIN
        "404":
          description: Receiver not found
  
  /api/transaction/{id}:
    get:
      tags: [Transaction]
      summary: Get transaction history for user or agent
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of transactions
        "403":
          description: Access denied
        "401":
          description: Unauthorized
  
  /api/cash-in:
    post:
      tags: [Transaction]
      summary: Agent cash-in to a user (no fee)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                receiverMobileNumber:
                  type: string
                amount:
                  type: number
                pin:
                  type: string
      responses:
        "201":
          description: Cash-in successful
        "403":
          description: Not an agent
        "401":
          description: Incorrect PIN
        "400":
          description: Validation or insufficient balance
        "404":
          description: Receiver not found
  
  /api/cash-out:
    post:
      tags: [Transaction]
      summary: User cashes out to an agent
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                agentMobileNumber:
                  type: string
                amount:
                  type: number
                pin:
                  type: string
      responses:
        "201":
          description: Cash-out successful
        "400":
          description: Validation error or insufficient balance
        "401":
          description: Incorrect PIN
        "403":
          description: Only users can initiate
        "404":
          description: Agent not found or unapproved
